version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airport_postgres
    environment:
      POSTGRES_DB: airport_system
      POSTGRES_USER: airport
      POSTGRES_PASSWORD: plane123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airport -d airport_system"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
